#!/bin/bash
#Script Variables
HOST='172.104.51.65';
USER='argosus_dmob';
PASS='argosus_dmob';
DBNAME='argosus_dmob';
PORT_TCP='5666';
PORT_UDP='5666';
SUB_DOMAIN=kupg.argos24.us
MYIP=$(wget -qO- icanhazip.com);
server_ip=$(curl -s https://api.ipify.org)
404: Not Found